### ISSUE TITLE
Ensure different protocols don't use the same Identifier

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#18]
The Storage struct manages state for different protocol instances simultaneously. It does so partly by indexing data based on the `Identifier` (think session ID). There are some `StorableType`s which are used in multiple different protocols, such as ProgressStore and BroadcastSet. It is unclear what could happen if, say, a KeyGen and a Presign had the same Identifier, but it could possibly result in destructive interference or an avenue for an exploit. 

Broadcast is an exception to this, as it is currently designed to use the same Identifier as its parent protocol.

**Comment by marsella** [comment]
Per discussion on 11/28/2022, we're not sure what the best approach to fixing this is. Some potential options include

- Add a protocol flag to the identifier
This would tie the ID to a specific protocol, so that there's an easy way to validate whether it's being reused or would cause storage interference.

- Ignore reused IDs
When a participant receives a "start protocol" message, they check their list of in-use IDs to see if it conflicts. If so, they ignore it.
This approach would also need to defend against attacks where a misbehaving participant sends a mid-protocol message with the repeated ID (the receiver would have to notice that its storage doesn't correspond with the protocol).

In the call, we decided to start this issue by writing tests to see what the failure behavior currently is for this scenario, then re-evaluating.

**Comment by marsella** [comment]
This issue is no longer relevant with the change to make Participants single-session (#216) and the removal of session IDs as a database index (#217).
