### ISSUE TITLE
Add auxinfo public parameters to presigning context

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#241]
The `Context` for presigning should include every party's public parameters from auxinfo (denoted (**N**, **s**, **t**) in the paper, and called `AuxInfoPublic` in our code). 

With #236, these should be guaranteed available to a `PresignParticipant`, since they'll be passed as input.

- [x] Decide an ordering for the public material (e.g. sorted by participant ID, sorted by `N`?)
- [x] Add to the `Context` for presign
- [x] Update the context method to return it

**Comment by Ra1issa** [comment]
Regarding this epic I have two comments: 

(1) Unfortunately it seems that adding  the public Auxiliary Information will be tricky because it will require changing the current interface so that `PresignParticipant` can store `AuxInfoPublic` for a given participant `id`.  Currently `InnerProtocolParticipant::retrieve_context(...)` and `ProtocolParticipant::new(...)` do not expect taking a parameter of type `AuxInfoPublic`. 

(2) I foresee the `PresignContext` looking something like this: 

```rust

pub struct PresignContext {
    shared_context: SharedContext,
    auxinfo_public: AuxInfoPublic,
}
impl ProofContext for PresignContext {
    fn as_bytes(&self) -> Result<Vec<u8>> {
        Ok([
            self.shared_context.as_bytes()?,
            bincode::serialize(&self.auxinfo_public)
                .map_err(|_| InternalError::InternalInvariantFailed)?,
        ]
        .concat())
    }
}

impl PresignContext {
    pub(crate) fn collect<P: InnerProtocolParticipant>(
        auxinfo_public: AuxInfoPublic,
        p: &P,
    ) -> Self {
        Self {
            shared_context: SharedContext::collect(p),
            auxinfo_public,
        }
    }
}
```
