### ISSUE TITLE
Add tests to allow for the concurrent execution of subprotocols

### ISSUE THREAD

**Issue by tyurek** [boltlabs-inc/tss-ecdsa#27]
In the current main end-to-end test in protocol.rs, the three phases (Keygen, Auxinfo, Presign) are called sequentially, where one must finish before the next one starts. This is seen through the use of functions like `is_auxinfo_done` being called before initializing Presign.

It may be beneficial to be able to begin other protocol phases before hearing back from every node, both as a matter of improving concrete performance now and being able to better handle crashes when implementing the t-out-of-N threshold variant of this scheme (specifically, handling this well would allow for handling different parties crashing during different subprotocols).

As an added benefit, this would reduce the amount of work that needs to be done externally, as a protocol coordinator would not need to check that once subprotocol finished before starting another.

Adding these tests is likely to reveal some changes that need to be made to the main codebase, such as stashing Presign messages received before Keygen and Auxinfo finish

**Comment by marsella** [comment]
I'm going to close this issue for a few reasons:
- With our current product, it's more important to be confident in the protocol correctness than efficiency. Since the protocols + security proof as written in the paper expect one protocol to end before the next begins, I'd like to encode that into the library.
- It feels premature to me to start thinking about handling crashes when we move to t-of-N; I'm expecting potentially significant code refactors at that point and I don't want to build stuff now that might get refactored away when we get to that step
